import iconImg from '../assets/images/site/icon.svg';
import ogDefaultImg from '../assets/images/site/og-default.png';
import type {
  GiscusConfig,
  NavigationConfig,
  SiteConfig,
} from '@tsche/astro-blog-theme/config';

/**
 * Global site configuration.
 * Edit values here to rebrand the site. All values are typed and consumed
 * across layouts, components, RSS, sitemap, and SEO.
 */

// Export imported site images for use in components
export const SITE_IMAGES = {
  avatar: iconImg,
  favicon: iconImg,
  ogDefault: ogDefaultImg,
} as const;

/**
 * GitHub coordinates, configurable by the deployment environment.
 */
const GITHUB_HANDLE = 'pydongery';
const GITHUB_REPO = 'blog';

/**
 * Public GitHub coordinates of the deployed source. Useful for custom links
 * and integrations that need a repository URL.
 */
export const REPO = {
  handle: GITHUB_HANDLE,
  name: GITHUB_REPO,
  url: GITHUB_HANDLE ? `https://github.com/${GITHUB_HANDLE}/${GITHUB_REPO}` : 'https://github.com',
} as const;

export const SITE: SiteConfig = {
  // ==========================================
  // ✅ SAFE TO EDIT (Content & Presentation)
  // ==========================================

  /** Default site title used as homepage <title> and meta. */
  title: 'Pydong',
  /** Site tagline / description. */
  description:
    'Python shenanigans, language experiments, metaprogramming, compilers, and other technical malarkey.',
  /** Content types published by this site. Keys select theme styling/layout. */
  contentTypes: {
    articles: {
      label: 'Articles',
      singularLabel: 'Article',
      description: 'Long-form Python articles',
      eyebrow: 'Long form',
      landingPageLimit: 5,
      postsPerPage: 8,
    },
    updates: {
      label: 'Updates',
      singularLabel: 'Update',
      description: 'Python project and site updates',
      eyebrow: 'Recent changes',
      landingPageLimit: 5,
      postsPerPage: 8,
    },
  },
  /** Author/handle shown in footer + meta. */
  author: {
    name: 'Matthias Wippich',
    url: GITHUB_HANDLE ? `https://github.com/${GITHUB_HANDLE}` : undefined,
    avatar: iconImg,
    bio: 'Arcane Python, compilers, metaprogramming, and other shenanigans.',
  },
  contentLicense: {
    label: 'CC BY 4.0',
    url: 'https://creativecommons.org/licenses/by/4.0/',
  },
  /** Default OG image. */
  defaultOgImage: ogDefaultImg.src,
  /** Number of posts per page on listings. */
  postsPerPage: 8,
  /** Display ISO 8601 dates when true, otherwise readable English dates. */
  isoDates: false,
  /** Site-wide default for whether posts should display their featured image. */
  showFeaturedImages: true,
  /** Wrap the article body of posts and pages in a bordered, card-like container. */
  boxedArticles: false,
  /** Allow listing cards to grow when title/description content is longer. */
  dynamicPostCardHeight: false,
  overview: {
    hiddenTags: ['Python'],
  },
  /** Automatically generate Open Graph images for posts that don't have a `heroImage`. */
  autoOgImage: true,
  analytics: {
    umami: {
      websiteId: import.meta.env.PUBLIC_UMAMI_WEBSITE_ID ?? '',
      scriptUrl: 'https://cloud.umami.is/script.js',
      domains: ['pydong.org'],
      respectDoNotTrack: true,
    },
  },
  // ==========================================
  // ❗ CAN BREAK THINGS (EDIT WITH CAUTION)
  // ==========================================

  /** Public URL of the deployed site, no trailing slash. Breaks SEO/RSS if incorrect. */
  url: 'https://pydong.org',
};

export const NAV = {
  top: [
    { label: 'Articles', href: '/articles' },
    { label: 'Updates', href: '/updates' },
    { label: 'About', href: '/about' },
  ],
  footer: [
    { label: 'About', href: '/about' },
    { label: 'Archive', href: '/archives' },
    { label: 'Tags', href: '/tags' },
    { label: 'Categories', href: '/categories' },
    { label: 'RSS', href: '/rss.xml', icon: 'lucide:rss' },
    { label: 'Sitemap', href: '/sitemap-index.xml' },
  ],
} as const satisfies NavigationConfig;

/**
 * Giscus comments. Set `enabled: false` to globally disable. Individual
 * posts may opt out via frontmatter `comments: false`.
 *
 * Generate values at https://giscus.app and set them here.
 */
export const GISCUS: GiscusConfig = {
  enabled: true,
  repo: 'pydongery/blog',
  repoId: 'R_kgDOLhp4pg',
  category: 'Blog',
  categoryId: 'DIC_kwDOLhp4ps4CeCdq',
  mapping: 'og:title',
  strict: '0',
  emitMetadata: '0',
  inputPosition: 'bottom',
  loading: 'lazy',
};

/**
 * Pagefind runtime settings. The index itself is generated by `bun run pagefind`
 * after `astro build` and written to `dist/_pagefind/`.
 */
export const PAGEFIND = {
  /** Public path where the Pagefind bundle is served. */
  bundlePath: '/_pagefind/',
  /** Number of results to render at once. */
  pageSize: 10,
} as const;
